(() => {
  'use strict';
  const lista=document.getElementById('lista'),busca=document.getElementById('busca'),formacao=document.getElementById('formacao'),uf=document.getElementById('uf'),prazo=document.getElementById('prazo'),resumo=document.getElementById('resumo'),estado=document.getElementById('estado'); let concursos=[];
  const FALLBACK='https://raw.githubusercontent.com/tiago-ps/ColetorEventosGratuitos/main/imagens/concursos/concurso-fallback.png';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function render(){
    const q=norm(busca.value),f=formacao.value,u=uf.value,p=prazo.value;
    const itens=concursos.filter(c=>{const cargos=(c.cargos_compativeis||[]).map(x=>x.cargo).join(' '),temData=!!c.inscricoes_texto;return (!f||(c.formacoes_compativeis||[]).includes(f))&&(!u||c.uf===u)&&(!p||(p==='com-data'?temData:!temData))&&(!q||norm([c.titulo,c.cidade,c.uf,cargos,...(c.formacoes_compativeis||[])].join(' ')).includes(q))});
    resumo.textContent=`${itens.length} de ${concursos.length} oportunidades compatíveis com as formações acompanhadas.`;estado.hidden=itens.length>0;estado.textContent=itens.length?'':'Nenhum concurso corresponde aos filtros.';
    lista.innerHTML=itens.map(c=>{const local=[c.cidade,c.uf].filter(Boolean).join(' / '),cargos=(c.cargos_compativeis||[]).slice(0,5),img=c.imagem||FALLBACK;return `<article class="card"><img class="card-imagem" src="${esc(img)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${FALLBACK}'"><div class="card-corpo"><div class="badges"><span>CONCURSO</span>${(c.formacoes_compativeis||[]).map(x=>`<span class="formacao">${esc(x)}</span>`).join('')}</div><h2>${esc(c.titulo)}</h2>${local?`<p><strong>Localidade:</strong> ${esc(local)}</p>`:''}${c.inscricoes_texto?`<p><strong>Inscrições:</strong> ${esc(c.inscricoes_texto)}</p>`:`<p class="dado-pendente"><strong>Inscrições:</strong> consulte o edital</p>`}${c.remuneracao_faixa_texto?`<p><strong>Faixa de remuneração do concurso:</strong> ${esc(c.remuneracao_faixa_texto)}</p>`:''}${cargos.length?`<div class="cargos"><strong>Cargos possivelmente compatíveis:</strong><ul>${cargos.map(x=>`<li>${esc(x.cargo)}${x.vagas_texto?` — ${esc(x.vagas_texto)}`:''}</li>`).join('')}</ul></div>`:''}<p class="fonte">Fonte: PCI Concursos · seleção automática. Confirme requisitos, remuneração e vagas no edital.</p><a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Ver concurso e edital ↗</a></div></article>`}).join('');}
  fetch('concursos.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(data=>{concursos=Array.isArray(data.concursos)?data.concursos:[];const fs=[...new Set(concursos.flatMap(c=>c.formacoes_compativeis||[]))].sort((a,b)=>a.localeCompare(b,'pt-BR')),ufs=[...new Set(concursos.map(c=>c.uf).filter(Boolean))].sort();formacao.insertAdjacentHTML('beforeend',fs.map(f=>`<option>${esc(f)}</option>`).join(''));uf.insertAdjacentHTML('beforeend',ufs.map(x=>`<option>${esc(x)}</option>`).join(''));render()}).catch(e=>{resumo.textContent='Não foi possível carregar a base de concursos.';estado.hidden=false;estado.textContent=`Erro: ${e.message}`});
  [busca,formacao,uf,prazo].forEach(el=>el.addEventListener(el===busca?'input':'change',render));
})();
