(() => {
  'use strict';
  let cursos=[]; let carregando=null; let busca=''; let area=''; let instituicao=''; let carga='';
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const areas=c=>String(c.area||'').split(/\s*\/\s*|\s*;\s*|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);
  const horas=v=>{const m=String(v||'').match(/\d+(?:[.,]\d+)?/);return m?Number(m[0].replace(',','.')):0};
  function load(){if(carregando)return carregando;carregando=fetch(`cursos.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error(`HTTP ${r.status}`))).then(d=>{cursos=(Array.isArray(d.cursos)?d.cursos:[]).filter(c=>String(c.titulo||'').trim());return cursos}).catch(e=>{console.error('Cursos indisponíveis',e);cursos=[];return cursos});return carregando}
  function ensureOption(){document.querySelectorAll('select.agenda-content').forEach(s=>{if(!s.querySelector('option[value="courses"]')){const o=new Option('Cursos','courses');s.append(o)}})}
  function filtro(c){const q=norm(busca),texto=norm([c.titulo,c.instituicao,c.instituicao_parceira,c.area,c.competencias,c.descricao,c.publico_alvo,c.conteudo_programatico].join(' '));if(q&&!texto.includes(q))return false;if(area&&!areas(c).some(x=>norm(x)===area))return false;if(instituicao&&norm(c.instituicao)!==instituicao)return false;const h=horas(c.carga_horaria);if(carga==='curto'&&!(h>0&&h<=10))return false;if(carga==='medio'&&!(h>=11&&h<=40))return false;if(carga==='longo'&&!(h>40))return false;return true}
  function options(values,selected,first){return `<option value="">${esc(first)}</option>`+values.map(([v,l])=>`<option value="${esc(v)}"${v===selected?' selected':''}>${esc(l)}</option>`).join('')}
  function unique(fn){const m=new Map();cursos.forEach(c=>fn(c).forEach(x=>{const l=String(x||'').trim(),v=norm(l);if(l&&v&&!m.has(v))m.set(v,l)}));return [...m].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'))}
  function image(c){const u=/^https?:\/\//.test(c.imagem||'')?c.imagem:'';const inst=esc(c.instituicao||c.fonte||'Instituição');return u?`<img src="${esc(u)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove();this.parentElement.classList.add('without-image')">`:`<div class="course-institution-fallback"><strong>${inst}</strong></div>`}
  function card(c){const url=/^https?:\/\//.test(c.url||'')?c.url:'';const art=document.createElement('article');art.className='agenda-card agenda-course-card';art.innerHTML=`<div class="agenda-card-media">${image(c)}</div><div class="agenda-card-body"><div class="agenda-card-badges"><span>Curso online</span><span>Gratuito</span>${areas(c).slice(0,1).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="agenda-card-date">${c.carga_horaria?`${esc(c.carga_horaria)} h`:''}${c.prazo_conclusao_dias?` • ${esc(c.prazo_conclusao_dias)} dias`:''}</p><h2>${esc(c.titulo||'Curso')}</h2><p class="agenda-card-place">${esc(c.instituicao||c.fonte||'Instituição não informada')}</p><p class="agenda-card-description">${esc(c.descricao||'')}</p><div class="agenda-card-actions">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Acessar curso</a>`:''}</div></div>`;return art}
  function render(){const app=document.getElementById('app');if(!app)return;const lista=cursos.filter(filtro);document.body.classList.add('agenda-mode');document.body.classList.remove('panel-mode');app.innerHTML=`<div class="agenda-shell"><header class="agenda-header"><div class="agenda-heading"><img class="agenda-logo" src="imagens/marca/logo-mural-cultural.png" alt="Mural Cultural"><p class="agenda-eyebrow">Cursos Online Gratuitos</p></div><div class="agenda-header-actions"><button class="course-back-panel view-toggle" type="button">Modo painel</button></div></header><section class="agenda-tools agenda-tools-courses" aria-label="Pesquisar e filtrar cursos"><label class="agenda-search"><span>Pesquisar</span><input class="course-search" type="search" placeholder="Título, instituição, área ou tema" value="${esc(busca)}"></label><label><span>Conteúdo</span><select class="agenda-content"><option value="all">Todos</option><option value="events">Eventos</option><option value="books">Livros</option><option value="courses" selected>Cursos</option></select></label><label><span>Área</span><select class="course-area">${options(unique(c=>areas(c)),area,'Todas as áreas')}</select></label><label><span>Instituição</span><select class="course-inst">${options(unique(c=>[c.instituicao]),instituicao,'Todas as instituições')}</select></label><label><span>Carga horária</span><select class="course-load"><option value=""${!carga?' selected':''}>Qualquer duração</option><option value="curto"${carga==='curto'?' selected':''}>Até 10 h</option><option value="medio"${carga==='medio'?' selected':''}>11 a 40 h</option><option value="longo"${carga==='longo'?' selected':''}>Mais de 40 h</option></select></label></section><div class="agenda-results-count"><strong>${lista.length} ${lista.length===1?'curso encontrado':'cursos encontrados'}</strong></div><div class="agenda-results"><div class="agenda-list course-native-list"></div></div></div>`;const container=app.querySelector('.course-native-list');lista.forEach(c=>container.append(card(c)));app.querySelector('.course-search').addEventListener('input',e=>{busca=e.target.value;render()});app.querySelector('.course-area').addEventListener('change',e=>{area=e.target.value;render()});app.querySelector('.course-inst').addEventListener('change',e=>{instituicao=e.target.value;render()});app.querySelector('.course-load').addEventListener('change',e=>{carga=e.target.value;render()});app.querySelector('.course-back-panel').addEventListener('click',()=>location.reload())}
  document.addEventListener('change',e=>{const s=e.target.closest?.('select.agenda-content');if(!s)return;if(s.value==='courses'){e.stopImmediatePropagation();load().then(render)}},true);
  const observer=new MutationObserver(ensureOption);observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});ensureOption();load();
})();
