(() => {
  'use strict';
  const DATA_URL='cursos.json', SETTINGS_KEY='mural-cultural-cursos-painel-v1';
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const safe=v=>{try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
  let courses=[], courseIndex=0, timer=null;
  const areas=c=>String(c.area||'').split(/\s*\/\s*|\s*;\s*|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);
  const settings=()=>{try{return {...{enabled:false,weight:1},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {enabled:false,weight:1}}};
  const saveSettings=s=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}catch{}};
  function courseCard(c){const a=document.createElement('article');a.className='agenda-card agenda-course-card';const url=safe(c.url||c.link),image=safe(c.imagem);a.innerHTML=`<div class="agenda-card-media course-media">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:`<div class="course-institution-fallback"><strong>${esc(c.instituicao||'Instituição')}</strong></div>`}</div><div class="agenda-card-body"><div class="agenda-card-badges"><span>Curso</span><span>Online</span><span>Gratuito</span></div><p class="agenda-card-date">${esc(c.carga_horaria?`${c.carga_horaria} h`:'Formação online')}</p><h2>${esc(c.titulo||'Curso')}</h2><p class="agenda-card-place">${esc(c.instituicao||c.fonte||'Instituição')}</p><p class="agenda-card-description">${esc(c.descricao||'')}</p><div class="agenda-card-actions">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Acessar curso</a>`:''}</div></div>`;a.querySelector('img')?.addEventListener('error',e=>e.currentTarget.outerHTML=`<div class="course-institution-fallback"><strong>${esc(c.instituicao||'Instituição')}</strong></div>`);return a}
  function queryMatches(c,q){return !q||norm([c.titulo,c.instituicao,c.instituicao_parceira,c.area,c.competencias,c.descricao,c.publico_alvo].join(' ')).includes(q)}
  function selectedContent(){return document.querySelector('.agenda-content')?.value||'all'}
  function injectAgenda(){const select=document.querySelector('.agenda-content');if(select&&!select.querySelector('option[value="courses"]'))select.append(new Option('Cursos','courses'));const shell=document.querySelector('.agenda-shell');if(!shell||!courses.length)return;const content=selectedContent();if(!['all','courses'].includes(content))return;const container=shell.querySelector('.agenda-results')||shell.querySelector('.agenda-content-results')||shell.lastElementChild;if(!container||container.querySelector('.native-course-section'))return;const q=norm(document.querySelector('.agenda-search input')?.value||''),visible=courses.filter(c=>queryMatches(c,q));if(!visible.length)return;const section=document.createElement('section');section.className='agenda-content-section native-course-section';section.innerHTML=`<header class="agenda-section-header"><div><h2>Cursos online gratuitos</h2><span>${visible.length} resultados</span></div>${content==='all'?'<button type="button" class="agenda-section-action native-course-only">Ver todos os cursos →</button>':''}</header><div class="agenda-section-grid"></div>`;const grid=section.querySelector('.agenda-section-grid');visible.slice(0,content==='all'?12:visible.length).forEach(c=>grid.append(courseCard(c)));container.append(section);section.querySelector('.native-course-only')?.addEventListener('click',()=>{select.value='courses';select.dispatchEvent(new Event('change',{bubbles:true}))})}
  function ensurePanelControls(){const switches=document.querySelector('.panel-module-switches'),bookSection=document.querySelector('.panel-book-section');if(!switches||!bookSection)return;let toggle=switches.querySelector('.panel-module-courses');if(!toggle){const label=document.createElement('label');label.className='panel-module-toggle native-course-toggle';label.innerHTML='<input class="panel-module-courses" type="checkbox"><span>Cursos</span>';switches.append(label);toggle=label.querySelector('input')}let section=document.querySelector('.panel-course-section');if(!section){section=document.createElement('section');section.className='panel-config-section panel-course-section';section.innerHTML='<div class="panel-section-heading"><div><h3>Cursos</h3><p>Cursos online gratuitos de instituições consolidadas.</p></div><label class="panel-weight-field"><span>Frequência</span><select class="panel-course-weight"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option></select></label></div>';bookSection.after(section)}const s=settings(),weight=section.querySelector('.panel-course-weight');if(!toggle.dataset.bound){toggle.checked=s.enabled;weight.value=String(s.weight);toggle.addEventListener('change',()=>saveSettings({enabled:toggle.checked,weight:Number(weight.value)||1}));weight.addEventListener('change',()=>saveSettings({enabled:toggle.checked,weight:Number(weight.value)||1}));toggle.dataset.bound='1'}}
  function renderCourseInPanel(){const s=settings();if(!s.enabled||!courses.length||document.querySelector('.filter-overlay:not([hidden])'))return;const slide=document.querySelector('.slide');if(!slide)return;const c=courses[courseIndex++%courses.length],eventCopy=slide.querySelector('.event-copy'),bookCopy=slide.querySelector('.book-copy'),img=slide.querySelector('.event-image'),fallback=slide.querySelector('.image-fallback'),url=safe(c.url||c.link),image=safe(c.imagem);if(bookCopy)bookCopy.hidden=true;if(eventCopy){eventCopy.hidden=false;eventCopy.querySelector('.category').textContent='CURSO';eventCopy.querySelector('.free').textContent='GRATUITO';eventCopy.querySelector('.rating').hidden=true;eventCopy.querySelector('.city').textContent='ONLINE';eventCopy.querySelector('.event-title').textContent=c.titulo||'Curso';eventCopy.querySelector('.description').textContent=c.descricao||c.competencias||'';eventCopy.querySelector('.when').textContent=c.carga_horaria?`${c.carga_horaria} horas`:'Curso online';eventCopy.querySelector('.where-text').textContent=c.instituicao||c.fonte||'Instituição';eventCopy.querySelector('.map-link').hidden=true}if(img){img.hidden=!image;if(image)img.src=image}if(fallback){fallback.hidden=!!image;fallback.querySelector('.fallback-icon').textContent='🎓';fallback.querySelector('.fallback-label').textContent=c.instituicao||'Curso online'}slide.querySelector('.source-label').textContent='Acesse o curso';slide.querySelector('.source-url').textContent=url?new URL(url).hostname:'';slide.querySelector('.updated').textContent=c.area||'';const qr=slide.querySelector('.qr-code');if(qr&&url&&window.QRCode){qr.innerHTML='';new QRCode(qr,{text:url,width:128,height:128})}slide.querySelector('.qr-item-label').textContent='Abrir este curso'}
  function schedulePanelCourses(){clearInterval(timer);timer=setInterval(()=>{const s=settings();if(!s.enabled)return;const eventWeight=Number(document.querySelector('.panel-event-weight')?.value||5),bookWeight=Number(document.querySelector('.panel-book-weight')?.value||1),ratio=Math.max(1,Math.round((eventWeight+bookWeight)/(Number(s.weight)||1)));if(courseIndex%ratio===0)renderCourseInPanel();else courseIndex++},12000)}
  async function load(){try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();courses=(Array.isArray(d.cursos)?d.cursos:[]).filter(c=>String(c.titulo||'').trim()).map(c=>({...c,tipo_conteudo:'curso'}));window.MuralCourses={all:()=>courses.slice(),areas,settings};injectAgenda();ensurePanelControls();schedulePanelCourses()}catch(e){console.warn('Cursos indisponíveis',e)}}
  new MutationObserver(()=>requestAnimationFrame(()=>{injectAgenda();ensurePanelControls()})).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});document.addEventListener('input',e=>{if(e.target.matches('.agenda-search input'))setTimeout(injectAgenda,220)});load();
})();
