(() => {
  'use strict';
  const PANEL_ID='mural-cursos-overlay';
  function ensurePanel(){let o=document.getElementById(PANEL_ID);if(o)return o;o=document.createElement('div');o.id=PANEL_ID;o.className='mural-cursos-overlay';o.hidden=true;o.innerHTML=`<section class="mural-cursos-panel" role="dialog" aria-modal="true" aria-label="Cursos online gratuitos"><header class="mural-cursos-header"><div><span>Formação e oportunidades</span><strong>Cursos online gratuitos</strong></div><button type="button" class="mural-cursos-close" aria-label="Fechar cursos">×</button></header><iframe class="mural-cursos-frame" title="Catálogo de cursos online gratuitos" data-src="cursos.html?integrado=1"></iframe></section>`;document.body.append(o);const close=()=>{o.hidden=true;document.body.classList.remove('mural-cursos-open')};o.querySelector('.mural-cursos-close').addEventListener('click',close);o.addEventListener('click',e=>{if(e.target===o)close()});return o}
  function openCourses(){const o=ensurePanel(),f=o.querySelector('.mural-cursos-frame');if(!f.src)f.src=f.dataset.src;o.hidden=false;document.body.classList.add('mural-cursos-open');o.querySelector('.mural-cursos-close').focus()}
  function makeButton(c=''){const b=document.createElement('button');b.type='button';b.className=`mural-cursos-trigger ${c}`.trim();b.textContent='Cursos';b.setAttribute('aria-label','Abrir cursos online gratuitos');b.addEventListener('click',openCourses);return b}
  function enhance(){const actions=document.querySelector('.agenda-header-actions');if(actions&&!actions.querySelector('.mural-cursos-trigger')){const view=actions.querySelector('.view-toggle');actions.insertBefore(makeButton('mural-cursos-agenda-btn'),view||null)}const controls=document.querySelector('.slide .controls');if(controls&&!controls.querySelector('.mural-cursos-trigger')){const filter=controls.querySelector('.filter-btn'),b=makeButton('control-btn mural-cursos-panel-btn');b.innerHTML='<span aria-hidden="true">🎓</span><span class="mural-cursos-panel-label">Cursos</span>';controls.insertBefore(b,filter?filter.nextSibling:controls.firstChild)}const switches=document.querySelector('.panel-module-switches');if(switches&&!switches.querySelector('.mural-cursos-module-link')){const label=document.createElement('label');label.className='panel-module-toggle mural-cursos-module-link';label.innerHTML='<button type="button">Cursos</button><small>abrir catálogo</small>';label.querySelector('button').addEventListener('click',e=>{e.preventDefault();openCourses()});switches.append(label)}}
  document.addEventListener('keydown',e=>{const o=document.getElementById(PANEL_ID);if(e.key==='Escape'&&o&&!o.hidden){o.hidden=true;document.body.classList.remove('mural-cursos-open')}});enhance();new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});
})();
