(() => {
  'use strict';
  const DATA_URL = 'cursos.json';
  const state = { cursos: [], busca: '', area: '', instituicao: '', carga: '' };
  const $ = id => document.getElementById(id);
  const norm = v => String(v || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
  const esc = v => String(v || '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  function horas(v) { const m = String(v || '').match(/\d+(?:[.,]\d+)?/); return m ? Number(m[0].replace(',','.')) : 0; }
  function cargaOk(c) { const h=horas(c.carga_horaria); if(!state.carga)return true; if(state.carga==='curto')return h>0&&h<=10; if(state.carga==='medio')return h>=11&&h<=40; return h>40; }
  function texto(c){return norm([c.titulo,c.instituicao,c.instituicao_parceira,c.area,c.competencias,c.descricao,c.publico_alvo,c.conteudo_programatico].join(' '));}
  function visiveis(){return state.cursos.filter(c=>(!state.busca||texto(c).includes(norm(state.busca)))&&(!state.area||norm(c.area)===state.area)&&(!state.instituicao||norm(c.instituicao)===state.instituicao)&&cargaOk(c));}
  function opcoes(id, campo, label){const el=$(id), mapa=new Map(); state.cursos.forEach(c=>{const x=String(c[campo]||'').trim(); if(x&&!mapa.has(norm(x)))mapa.set(norm(x),x)}); [...mapa].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;el.append(o)});}
  function card(c){const a=document.createElement('article');a.className='curso-card'; const url=/^https?:\/\//.test(c.url||'')?c.url:''; const prazo=c.prazo_conclusao_dias?`${esc(c.prazo_conclusao_dias)} dias para concluir`:''; a.innerHTML=`<div class="badges"><span>Curso online</span><span>Gratuito</span>${c.area?`<span>${esc(c.area)}</span>`:''}</div><h2>${esc(c.titulo||'Curso')}</h2><p class="instituicao">${esc(c.instituicao||c.fonte||'Instituição não informada')}</p><div class="metas">${c.carga_horaria?`<span><b>Carga horária</b>${esc(c.carga_horaria)} h</span>`:''}${prazo?`<span><b>Prazo</b>${prazo}</span>`:''}${c.tipo?`<span><b>Oferta</b>${esc(c.tipo)}</span>`:''}</div>${c.descricao?`<p class="descricao">${esc(c.descricao)}</p>`:''}${c.publico_alvo?`<p class="publico"><b>Público-alvo:</b> ${esc(c.publico_alvo)}</p>`:''}<div class="acoes">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Acessar curso →</a>`:''}<span>${esc(c.fonte||'')}</span></div>`; return a;}
  function render(){const cursos=visiveis(),lista=$('lista');lista.replaceChildren(); $('total').textContent=`${cursos.length} ${cursos.length===1?'curso encontrado':'cursos encontrados'}`; cursos.forEach(c=>lista.append(card(c))); if(!cursos.length)lista.innerHTML='<div class="vazio"><h2>Nenhum curso encontrado</h2><p>Tente alterar os filtros ou a pesquisa.</p></div>';}
  async function load(){try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();state.cursos=Array.isArray(d.cursos)?d.cursos:[];opcoes('area','area');opcoes('instituicao','instituicao');if(d.coletado_em_utc){const dt=new Date(d.coletado_em_utc);$('atualizado').textContent=Number.isNaN(dt.getTime())?'':`Coleta atualizada em ${dt.toLocaleString('pt-BR')}`;}render();}catch(e){console.error(e);$('total').textContent='Cursos indisponíveis';$('erro').hidden=false;}}
  $('busca').addEventListener('input',e=>{state.busca=e.target.value;render()});$('area').addEventListener('change',e=>{state.area=e.target.value;render()});$('instituicao').addEventListener('change',e=>{state.instituicao=e.target.value;render()});$('carga').addEventListener('change',e=>{state.carga=e.target.value;render()});load();
})();
