(() => {
  'use strict';
  const DATA_URL='cursos.json';
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  let courses=[];
  const areas=c=>String(c.area||'').split(/\s*\/\s*|\s*;\s*|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);
  function courseCard(c){const a=document.createElement('article');a.className='agenda-card agenda-course-card';const url=/^https?:\/\//.test(c.url||'')?c.url:'';const image=/^https?:\/\//.test(c.imagem||'')?c.imagem:'';a.innerHTML=`<div class="agenda-card-media course-media">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:`<div class="course-institution-fallback"><strong>${esc(c.instituicao||'Instituição')}</strong></div>`}</div><div class="agenda-card-body"><div class="agenda-card-badges"><span>Curso</span><span>Online</span><span>Gratuito</span></div><p class="agenda-card-date">${esc(c.carga_horaria?`${c.carga_horaria} h`:'Formação online')}</p><h2>${esc(c.titulo||'Curso')}</h2><p class="agenda-card-place">${esc(c.instituicao||c.fonte||'Instituição')}</p><p class="agenda-card-description">${esc(c.descricao||'')}</p><div class="agenda-card-actions">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Acessar curso</a>`:''}</div></div>`;const img=a.querySelector('img');if(img)img.onerror=()=>{img.outerHTML=`<div class="course-institution-fallback"><strong>${esc(c.instituicao||'Instituição')}</strong></div>`};return a}
  function queryMatches(c,q){if(!q)return true;return norm([c.titulo,c.instituicao,c.instituicao_parceira,c.area,c.competencias,c.descricao,c.publico_alvo].join(' ')).includes(q)}
  function selectedContent(){return document.querySelector('.agenda-content')?.value||'all'}
  function currentQuery(){return norm(document.querySelector('.agenda-search input')?.value||'')}
  function injectOption(){const s=document.querySelector('.agenda-content');if(!s||s.querySelector('option[value="courses"]'))return;const o=new Option('Cursos','courses');s.append(o)}
  function injectCourses(){injectOption();const shell=document.querySelector('.agenda-shell');if(!shell||!courses.length)return;const content=selectedContent();if(content!=='all'&&content!=='courses')return;const container=shell.querySelector('.agenda-results')||shell.querySelector('.agenda-content-results')||shell.lastElementChild;if(!container)return;if(container.querySelector('.native-course-section'))return;const visible=courses.filter(c=>queryMatches(c,currentQuery()));if(!visible.length)return;const section=document.createElement('section');section.className='agenda-content-section native-course-section';const head=document.createElement('header');head.className='agenda-section-header';head.innerHTML=`<div><h2>Cursos online gratuitos</h2><span>${visible.length} resultados</span></div>${content==='all'?'<button type="button" class="agenda-section-action native-course-only">Ver todos os cursos →</button>':''}`;const grid=document.createElement('div');grid.className='agenda-section-grid';visible.slice(0,content==='all'?12:visible.length).forEach(c=>grid.append(courseCard(c)));section.append(head,grid);container.append(section);head.querySelector('.native-course-only')?.addEventListener('click',()=>{const s=document.querySelector('.agenda-content');if(s){s.value='courses';s.dispatchEvent(new Event('change',{bubbles:true}))}})}
  async function load(){try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();courses=(Array.isArray(d.cursos)?d.cursos:[]).filter(c=>String(c.titulo||'').trim()).map(c=>({...c,tipo_conteudo:'curso'}));window.MuralCourses={all:()=>courses.slice(),areas};injectCourses()}catch(e){console.warn('Cursos indisponíveis',e)}}
  new MutationObserver(()=>requestAnimationFrame(injectCourses)).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});document.addEventListener('input',e=>{if(e.target.matches('.agenda-search input'))setTimeout(injectCourses,220)});load();
})();
